import { UserProfile } from "./types";

export const MOCK_PROFILES: UserProfile[] = [
  {
    id: "harry_potter",
    displayName: "Harry Potter",
    email: "harry@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250",
    bio: "The Boy Who Lived. Gryffindor Seeker. Wand: 11\" Holly, phoenix feather core. Skilled in defensive charms, Patronus conjuring, and escaping Voldemort. Desperately needs help in Potions and Occlumency before Snape kicks me out.",
    skills: ["Defense Against the Dark Arts", "Broomstick Flying & Quidditch", "Expecto Patronum"],
    needs: ["Advanced Potions", "Occlumency & Mind Shielding", "Care of Magical Creatures"],
    credits: 7.5,
    rating: 4.8,
    totalReviews: 19,
    taughtHours: 24,
    location: "Gryffindor Tower",
    isMock: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "hermione_granger",
    displayName: "Hermione Granger",
    email: "hermione@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250",
    bio: "Gryffindor Prefect and brightest witch of our age. Wand: 10¾\" Vine wood, dragon heartstring core. Can tutor any subject including ancient runes, advanced charms, and transfiguration history. Want to understand Muggle Studies from a modern perspective and get some practical tips on broomstick high-speed cornering.",
    skills: ["Ancient Runes Translation", "Charms & Alohomora", "Advanced Transfiguration"],
    needs: ["Muggle Studies & Culture", "Broomstick Flying & Quidditch", "Care of Magical Creatures"],
    credits: 15.0,
    rating: 5.0,
    totalReviews: 32,
    taughtHours: 45,
    location: "Hogwarts Library",
    isMock: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "draco_malfoy",
    displayName: "Draco Malfoy",
    email: "draco@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250",
    bio: "Slytherin Seeker and pureblood heir. Wand: 10\" Hawthorn, unicorn hair core. Highly proficient in Potions crafting, Occlumency, and competitive Quidditch tactics. Looking for someone competent to teach me Advanced Transfiguration or defensive dueling. No mudbloods or squibs.",
    skills: ["Advanced Potions", "Occlumency & Mind Shielding", "Slytherin Quidditch Tactics"],
    needs: ["Defense Against the Dark Arts", "Advanced Transfiguration", "Ancient Runes Translation"],
    credits: 4.0,
    rating: 4.5,
    totalReviews: 11,
    taughtHours: 12,
    location: "Slytherin Dungeon",
    isMock: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "luna_lovegood",
    displayName: "Luna Lovegood",
    email: "luna@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=250",
    bio: "Ravenclaw. Wand: wood and core unknown. Let's talk about Nargles, Wrackspurts, or finding Crumple-Horned Snorkacks! Happy to teach Care of Magical Creatures (especially Thestrals) or Spectrespecs craft. Looking to learn defensive charms or how to make a perfect Herbology cure for Dirigible plums.",
    skills: ["Care of Magical Creatures", "Spectrespecs Crafting", "Ravenclaw Riddles"],
    needs: ["Expecto Patronum", "Herbology & Venomous Tentacula", "Charms & Alohomora"],
    credits: 8.0,
    rating: 4.9,
    totalReviews: 15,
    taughtHours: 18,
    location: "Ravenclaw Common Room",
    isMock: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "neville_longbottom",
    displayName: "Neville Longbottom",
    email: "neville@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250",
    bio: "Gryffindor. Wand: 13\" Cherry, unicorn hair. Expert in Herbology, Venomous Tentacula cultivation, and Gillyweed harvesting. Can help anyone with plant identification and potting mandrakes safely. Need serious remedial assistance in Charms and Potions before Snape fails me again.",
    skills: ["Herbology & Venomous Tentacula", "Gillyweed Harvesting", "Sword of Gryffindor Handling"],
    needs: ["Charms & Alohomora", "Advanced Potions", "Defense Against the Dark Arts"],
    credits: 5.0,
    rating: 4.7,
    totalReviews: 14,
    taughtHours: 16,
    location: "Hogwarts Greenhouse 3",
    isMock: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "cedric_diggory",
    displayName: "Cedric Diggory",
    email: "cedric@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250",
    bio: "Hufflepuff Prefect and Triwizard Champion. Wand: 12¼\" Ash with unicorn hair. Dedicated to fair play, Transfiguration duels, and Quidditch Seeker maneuvers. Always glad to mentor younger years in broom navigation or bubble-head charms.",
    skills: ["Transfiguration & Bubble-Head Charm", "Quidditch Seeker Tactics", "Triwizard Defense"],
    needs: ["Ancient Runes Translation", "Occlumency & Mind Shielding", "Advanced Potions"],
    credits: 10.0,
    rating: 4.9,
    totalReviews: 22,
    taughtHours: 30,
    location: "Hufflepuff Common Room",
    isMock: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "cho_chang",
    displayName: "Cho Chang",
    email: "cho@hogwarts.edu",
    photoURL: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250",
    bio: "Ravenclaw Seeker. Wand: 9\" Willow, dragon heartstring. Passionate about aerial charms, patronus charm training (Swan), and charms theory. Wanting to improve defense against dark curses.",
    skills: ["Charms & Alohomora", "Expecto Patronum", "Broomstick Flying & Quidditch"],
    needs: ["Defense Against the Dark Arts", "Advanced Potions", "Herbology & Venomous Tentacula"],
    credits: 6.5,
    rating: 4.8,
    totalReviews: 16,
    taughtHours: 20,
    location: "Ravenclaw Tower",
    isMock: true,
    createdAt: new Date().toISOString()
  }
];
